<a href="https://colab.research.google.com/github/TMRatul49/Early-Stage-Fire-Detection-Robot/blob/main/Lab%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [9]:
a = np.array([1,2,3])
a


array([1, 2, 3])

In [8]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
 np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
 d = np.arange(10,25,5)
 d

array([10, 15, 20])

In [18]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
 e = np.full((2,2),7)
 e

array([[7, 7],
       [7, 7]])

In [20]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [21]:
np.random.random((2,2))

array([[0.00290421, 0.62452907],
       [0.22949806, 0.3975377 ]])

In [22]:
 np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])